// <auto-generated />
using System;
using ASPCTS.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASPCTS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250421134825_AtualizacaoRelacionamentos")]
    partial class AtualizacaoRelacionamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASPCTS.Models.Atividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Concluida")
                        .HasColumnType("bit");

                    b.Property<int>("CriancaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CriancaId");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("ASPCTS.Models.Crianca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaiId")
                        .HasColumnType("int");

                    b.Property<int?>("PaiId1")
                        .HasColumnType("int");

                    b.Property<int?>("PsicologoId")
                        .HasColumnType("int");

                    b.Property<int?>("PsicologoId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaiId");

                    b.HasIndex("PaiId1");

                    b.HasIndex("PsicologoId");

                    b.HasIndex("PsicologoId1");

                    b.ToTable("Criancas");
                });

            modelBuilder.Entity("ASPCTS.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator().HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ASPCTS.Models.Pai", b =>
                {
                    b.HasBaseType("ASPCTS.Models.Usuario");

                    b.Property<int?>("PsicologoId")
                        .HasColumnType("int");

                    b.HasIndex("PsicologoId");

                    b.HasDiscriminator().HasValue("Pai");
                });

            modelBuilder.Entity("ASPCTS.Models.Psicologo", b =>
                {
                    b.HasBaseType("ASPCTS.Models.Usuario");

                    b.Property<string>("CRP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Psicologo");
                });

            modelBuilder.Entity("ASPCTS.Models.Atividade", b =>
                {
                    b.HasOne("ASPCTS.Models.Crianca", "Crianca")
                        .WithMany("Atividades")
                        .HasForeignKey("CriancaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crianca");
                });

            modelBuilder.Entity("ASPCTS.Models.Crianca", b =>
                {
                    b.HasOne("ASPCTS.Models.Pai", "Pai")
                        .WithMany()
                        .HasForeignKey("PaiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ASPCTS.Models.Pai", null)
                        .WithMany("Criancas")
                        .HasForeignKey("PaiId1");

                    b.HasOne("ASPCTS.Models.Psicologo", "Psicologo")
                        .WithMany()
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ASPCTS.Models.Psicologo", null)
                        .WithMany("Criancas")
                        .HasForeignKey("PsicologoId1");

                    b.Navigation("Pai");

                    b.Navigation("Psicologo");
                });

            modelBuilder.Entity("ASPCTS.Models.Pai", b =>
                {
                    b.HasOne("ASPCTS.Models.Psicologo", "Psicologo")
                        .WithMany()
                        .HasForeignKey("PsicologoId");

                    b.Navigation("Psicologo");
                });

            modelBuilder.Entity("ASPCTS.Models.Crianca", b =>
                {
                    b.Navigation("Atividades");
                });

            modelBuilder.Entity("ASPCTS.Models.Pai", b =>
                {
                    b.Navigation("Criancas");
                });

            modelBuilder.Entity("ASPCTS.Models.Psicologo", b =>
                {
                    b.Navigation("Criancas");
                });
#pragma warning restore 612, 618
        }
    }
}
